package com.factfeed.backend.model.repository;

import com.factfeed.backend.model.entity.AggregatedContent;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AggregatedContentRepository extends JpaRepository<AggregatedContent, Long> {

    /**
     * Find aggregated content by event ID
     */
    Optional<AggregatedContent> findByEventId(Long eventId);

    /**
     * Find recent aggregated content
     */
    @Query("SELECT ac FROM AggregatedContent ac WHERE ac.createdAt >= :fromDate ORDER BY ac.createdAt DESC")
    Page<AggregatedContent> findRecentContent(@Param("fromDate") LocalDateTime fromDate, Pageable pageable);

    /**
     * Find content that needs regeneration (old or low confidence)
     */
    @Query("SELECT ac FROM AggregatedContent ac WHERE " +
            "ac.updatedAt < :beforeDate OR ac.confidenceScore < :minConfidence")
    List<AggregatedContent> findContentNeedingRegeneration(@Param("beforeDate") LocalDateTime beforeDate,
                                                           @Param("minConfidence") Double minConfidence);

    /**
     * Search aggregated content by title or summary
     */
    @Query("SELECT ac FROM AggregatedContent ac WHERE " +
            "LOWER(ac.aggregatedTitle) LIKE LOWER(CONCAT('%', :keyword, '%')) OR " +
            "LOWER(ac.aggregatedSummary) LIKE LOWER(CONCAT('%', :keyword, '%'))")
    Page<AggregatedContent> searchContent(@Param("keyword") String keyword, Pageable pageable);

    /**
     * Find content with high confidence scores
     */
    @Query("SELECT ac FROM AggregatedContent ac WHERE ac.confidenceScore >= :minScore ORDER BY ac.confidenceScore DESC")
    Page<AggregatedContent> findHighConfidenceContent(@Param("minScore") Double minScore, Pageable pageable);

    /**
     * Find content with multiple sources
     */
    @Query("SELECT ac FROM AggregatedContent ac WHERE ac.sourceCount >= :minSources ORDER BY ac.sourceCount DESC")
    Page<AggregatedContent> findContentWithMultipleSources(@Param("minSources") Integer minSources, Pageable pageable);

    /**
     * Find content generated by specific model
     */
    Page<AggregatedContent> findByGeneratedBy(String generatedBy, Pageable pageable);

    /**
     * Count content created since a given time (use start of day for today's count)
     */
    @Query("SELECT COUNT(ac) FROM AggregatedContent ac WHERE ac.createdAt >= :fromDate")
    long countCreatedSince(@Param("fromDate") java.time.LocalDateTime fromDate);
}